### ISSUE TITLE
Some additional resources

### ISSUE THREAD

**Issue by ffesseler** [wbinnssmith/awesome-promises#3]
> This document is intended to explain how promises work and why this
> implementation works its particular way by building a promise library
> incrementally and reviewing all of its major design decisions.  This is
> intended to leave the reader at liberty to experiment with variations
> of this implementation that suit their own requirements, without missing
> any important details.

https://github.com/kriskowal/q/tree/v1/design

Would be a great addition to the list I guess !

**Comment by ffesseler** [comment]
Other useful resources I've collected over the years that could be included : 

[Promises/A+ Spec](https://promisesaplus.com/)
[Detailed tutorial](http://www.mattgreer.org/articles/promises-in-wicked-detail/)
[Promise Anti-patterns](http://taoofcode.net/promise-anti-patterns/)
[Writing Promise-Using Specifications](https://www.w3.org/2001/tag/doc/promises-guide)

**Comment by ffesseler** [comment]
Tell me which ones you'd like to include on your list and I will create a PR if needed

**Comment by wbinnssmith** [comment]
I'm hesitant to include @domenic's "Writing Promise-Using Specifications" since on the surface it doesn't cater towards *users* of promises and instead toward those who are writing specs that involve promises (like the service worker stuff on that page). That said, it looks useful to folks who are writing libraries with promise APIs and, after having read it, I think there's a ton in there for app developers who use promise APIs internally. Knowing when to use something is often more valuable than knowing how to use it :stuck_out_tongue: 

The spec itself is definitely a bit much to include as an introductory resource (though it is a lot less dense than most).

In general I'm more and more thinking that the list should divide the resources list into introductory ones and advanced ones. If we can make that happen I'd love to accept all of the ones you've included — they're all fantastic :smile:

**Comment by ffesseler** [comment]
> In general I'm more and more thinking that the list should divide the resources list into introductory 
> ones and advanced ones. If we can make that happen I'd love to accept all of the ones you've included > — they're all fantastic :smile:

Yes, that's probably the best thing to do as it will help developers to filter the resources according to their current knowledge of promises.

**Comment by wbinnssmith** [comment]
Just divided the resources into for-beginners, deep dive, and references. Feel free to add your resources to the respective sections!
